#pragma once

#include <vector>

#include "core/BatchCcmm.h"
#include "core/CiLift.h"
#include "core/Container.h"
#include "core/Context.h"
#include "core/EvkMap.h"
#include "core/RingSwitch.h"

namespace cheddar {

/**
 * @brief The conjugate-invariant CC-MM chain: [SYLPH] table 4's product row,
 * rebuilt for R+, where the small ring cannot run [KANG] itself (Doing.md
 * 1.5bk) and the product makes a keyless detour through the ordinary ring of
 * the same conductor:
 *
 *     num_cts x R+_big  --RingSwitch-->  d x R+_small
 *                       --CiLift-->      d x R_(2 small)
 *                       --[KANG] Alg.4 at 2k-->
 *                       --CiDescend-->   d x R+_small
 *                       --SwitchBack-->  num_cts x R+_big
 *
 * ## How this differs from `SwitchedCcmmHandler`, and why
 *
 * **1. The product runs on the lifted ring.** TWEAK's monomials do not exist
 * in the c-basis, so the small parts cross to the degree-2n ordinary ring
 * (`CiLiftHandler`, keyless both ways), run Algorithm 4 at sub-degree `2k`
 * -- a lifted CI block of sub-degree k is an ordinary block of sub-degree 2k,
 * with the same d and the same stride -- and come back through the trace.
 *
 * **2. The half-contraction contract (Doing.md 1.5bl).** The lift is not
 * block-clean: c_i = X^i - X^(N-i) splits across ordinary blocks i and d-i,
 * so per lane a lifted bundle is Lambda = I + w^-1 P E of the CI batch and a
 * full contraction would compute A (I + cos(theta) P E) B. The contract that
 * removes the twist identically: the lhs bundle supplies only columns
 * x < d/2 -- so `Multiply` takes **num_cts / 2** lhs ciphertexts and pads
 * the bundle with exact zeros, which also skips half the switches and lifts
 * -- and the rhs data must be confined to CI SinC blocks x < d/2 of every
 * part. The second half is a DATA contract on the caller: it cannot be read
 * off a ciphertext, and 1.5bl measured what breaks without it. The free
 * indices stay full: the result is `num_cts` big ciphertexts carrying the
 * per-lane real products (d x d/2)(d/2 x d).
 *
 * **3. There is no slot-level layout.** The ordinary layout's `Locate` rests
 * on two identities the CI chain does not have: `EvaluateSlotToSinC` has no
 * conjugate-invariant form yet, and the CI ring switch does not redistribute
 * SinC blocks by `i = j + rank * i'` -- its parts are the block-level banded
 * scan of the big blocks (Doing.md 1.5bj). So the layout here is stated at
 * the **part level**: entry (row, column, lane) lives in small ciphertext
 * `column` at CI SinC index `row * k + lane`, and a big operand ciphertext
 * is, in coefficients, the banded two-term recomposition of its `rank`
 * parts -- the exact inverse of what the switch computes, which is how a
 * caller (or the test) assembles one.
 *
 * ## Scale
 *
 * One level, spent inside Algorithm 4. The descent's trace doubles the
 * message and the factor rides the recorded scale (Doing.md 1.5bk), so the
 * output lands at **twice** the canonical scale of `level - 1` -- exact, and
 * a downstream plaintext constant absorbs the half for free.
 *
 * ## Keys, on three rings
 *
 * The forward and inverse ring-switching keys on the switching Context; the
 * `d - 1` ScrambleAuto automorphism keys plus a multiplication key on the
 * LIFTED ring, generated by the ordinary keygen from the adopted secret
 * `CiLiftHandler::LiftSecret(small secret)`. The lift and descent themselves
 * are keyless.
 *
 * @tparam word uint32_t or uint64_t
 */
struct CiSwitchedCcmmLayout {
  int big_degree = 0;    ///< the conjugate-invariant big ring's degree
  int small_degree = 0;  ///< the conjugate-invariant product ring's degree
  int sub_degree = 0;    ///< k; the lifted ring runs Algorithm 4 at 2k

  int rank = 0;         ///< big_degree / small_degree, parts per switch
  int dim = 0;          ///< d = small_degree / sub_degree, the matrix width
  int lanes = 0;        ///< k REAL lanes -- the subring is totally real
  int num_cts = 0;      ///< d / rank, big ciphertexts for the rhs operand
  int contraction = 0;  ///< d / 2, the contract's inner width

  CiSwitchedCcmmLayout() = default;
  CiSwitchedCcmmLayout(int big_degree, int small_degree, int sub_degree);

  /**
   * @brief Where entry `(row, column, lane)` of an operand lives, at the
   * part level: `part` is the small-ciphertext index (part `column % rank`
   * of big ciphertext `column / rank`), `index` the CI SinC message index
   * within it. The big ciphertext itself is the banded recomposition of its
   * parts' coefficients; there is no per-entry slot address on R+.
   */
  void LocatePart(int row, int column, int lane, int &part, int &index) const;

  /// The inverse of LocatePart.
  bool PositionPart(int part, int index, int &row, int &column,
                    int &lane) const;
};

template <typename word>
class CiSwitchedCcmmHandler {
 private:
  using Ct = Ciphertext<word>;
  using Evk = EvaluationKey<word>;

 public:
  /**
   * @param switch_ctx the conjugate-invariant big-ring Context that hosts
   *        the ring-switching key switch (`ci_ringswitch16_35` in the
   *        shipped pair)
   * @param small_ctx the conjugate-invariant product ring (`ci12_35`)
   * @param lifted_ctx the ORDINARY ring of the small ring's conductor,
   *        twice its degree, same primes at every level
   *        (`ringdegree13_35`); its keys live on the lifted secret
   * @param sub_degree k, the CI SinC sub-degree of the operands
   */
  CiSwitchedCcmmHandler(ConstContextPtr<word> switch_ctx,
                        ConstContextPtr<word> small_ctx,
                        ConstContextPtr<word> lifted_ctx, int sub_degree);

  // disable copying (or moving also)
  CiSwitchedCcmmHandler(const CiSwitchedCcmmHandler &) = delete;
  CiSwitchedCcmmHandler &operator=(const CiSwitchedCcmmHandler &) = delete;

  const CiSwitchedCcmmLayout &GetLayout() const { return layout_; }

  /// Automorphism indices the three CMT calls need, on the LIFTED ring.
  std::vector<int> LiftedRotationIndices() const {
    return ccmm_.RotationIndices(2 * layout_.sub_degree);
  }

  /**
   * @brief `res = lhs * rhs` under the half-contraction contract: one
   * `(d x d/2)(d/2 x d)` real product per lane, one level.
   *
   * @param res output, `num_cts` big ciphertexts, one level below the
   *        inputs, at TWICE the canonical scale of that level
   * @param lhs `num_cts / 2` big ciphertexts -- columns `x < d/2`; the
   *        dead half of the bundle is supplied as exact zeros here
   * @param rhs `num_cts` big ciphertexts whose parts carry data only in CI
   *        SinC blocks `x < d/2` (the caller's contract; unchecked)
   * @param swk the forward ring-switching key, from
   *        `UserInterface::PrepareRingSwitchKey` on the switching Context
   * @param inv_swk the inverse one
   * @param lifted_evk the lifted ring's automorphism and multiplication
   *        keys, on the adopted secret `CiLiftHandler::LiftSecret`
   */
  void Multiply(std::vector<Ct> &res, const std::vector<Ct> &lhs,
                const std::vector<Ct> &rhs, const Evk &swk, const Evk &inv_swk,
                const EvkMap<word> &lifted_evk) const;

 private:
  // Switch `operand` (its size() big ciphertexts) down and lift every part;
  // res is resized to d and positions beyond size() * rank become exact
  // zero ciphertexts at the lifted ring.
  void DescendAndLift(std::vector<Ct> &res,
                      const std::vector<Ct> &operand, const Evk &swk) const;

  ConstContextPtr<word> switch_ctx_;
  ConstContextPtr<word> small_ctx_;
  ConstContextPtr<word> lifted_ctx_;
  CiSwitchedCcmmLayout layout_;
  RingSwitchHandler<word> switcher_;
  CiLiftHandler<word> lift_;
  BatchCcmmHandler<word> ccmm_;
};

}  // namespace cheddar
